<?php
$frases_de_exito = [
    "Cuando te encuentres a ti mismo al lado de la mayoría, es tiempo de parar y reflexionar (Mark Twain)",
    "No tengas miedo de renunciar a lo bueno para ir a por lo grandioso (John D. Rockefeller)",
    "Tienes que aprender las reglas del juego y después jugar mejor que nadie (Albert Einstein)",
    "Si quieres hacer un cambio permanente, deja de centrarte en el tamaño de tus problemas y céntrate en tu tamaño (T. Harv Eker)",
    "El punto de partida de todo logro es el deseo (Napoleon Hill)",
    "Sin continuo crecimiento y perseverancia, palabras como mejora, logro y éxito no tienen significado (Benjamin Franklin)",
    "Reunirse es el comienzo; mantenerse juntos es el progreso; trabajar juntos es el éxito (Henry Ford)",
    "El éxito depende de la preparación previa, y sin ella seguro que llega el fracaso (Confucio)",
    "Nuestra mayor gloria no esta en fracasar nunca, sino en levantarnos cada vez que caemos (Confucio)",
    "Identifica tus problemas, pero pon tu poder y energía en las soluciones (Tony Robbins)",
    "Un hombre exitoso es el que es capaz de construir algo con los ladrillos que otros le han tirado (David Brinkley)",
    "Toma una idea. Hazla tu vida: piensa sobre ella, sueña sobre ella, vívela. Deja que tus músculos, cerebro, nervios y cada parte de tu cuerpo se llenen de esa idea. Luego deja todas las demás ideas solas. Ese es el camino hacia el éxito (Swami Vivekananda)",
    "Todo éxito tiene lugar fuera de la zona de confort (Michael John Bobak)",
    "La diferencia entre una persona exitosa y otros no es la falta de fuerza o falta de conocimiento, sino la falta de voluntad (Vince Lombardi)",
    "Ninguna pieza maestra fue creada por un artista perezoso",
    "La cuestión no es quién me va a dejar, es quién me va a parar (Ayn Rand)",
    "El éxito consiste en ir de fracaso a fracaso sin perder el entusiasmo (Winston Churchill)",
    "Tienes que esperar grandes cosas de ti mismo antes de hacerlas (Michael Jordan)",
    "Muchos de los fracasos en la vida de las personas ocurren cuando no se dieron cuenta lo cerca que estaban del éxito cuando abandonaron (Thomas A. Edison)",
    "Todos tus sueños se pueden convertir en realidad si tienes el coraje de perseguirlos (Walt Disney)",
    "Desarrolla el éxito desde los fracasos. El desaliento y el fracaso son dos piedras seguras hacia el éxito (Dale Carnegie)",
    "El éxito no es el final, el fracaso no es fatal; es el coraje de continuar lo que cuenta (Winston Churchill)",
    "Ten siempre en mente que tu propia voluntad de tener éxito es mucho más importante que cualquier otra cosa (Abraham Lincoln)",
    "Para poder triunfar, tu deseo de tener éxito debe ser mayor que tu miedo a fracasar (Bill Cosby)",
    "Veinte años más tarde estarás más decepcionado por las cosas que no hiciste que por las que hiciste (Mark Twain)",
    "El éxito consiste en crear beneficio para todos y disfrutar del proceso. Si te puedes enfocar en eso y adoptar la definición, el éxito es tuyo (Kelly Kim)",
    "La distancia entre locura y genio solo se mide con el éxito (Bruce Feirstein)",
    "El secreto de una vida exitosa es encontrar cuál es tu destino y entonces perseguirlo (Henry Ford)",
    "Solo cuando la oruga creyó que el mundo terminaba se transformó en mariposa (Proverbio)",
    "No he fracasado, he encontrado 10.000 formas que no funcionan (Thomas A. Edison)",
    "El hombre exitoso es un hombre promedio, con una capacidad de enfoque similar al láser (Bruce Lee)",
    "La gente raramente tiene éxito en algo antes de divertirse en lo que hacen (Dale Carnegie)",
    "He visto que cuanto más trabajo, más suerte parece que tengo (Thomas Jefferson)",
    "Si no estás dispuesto a arriesgar lo inusual, tendrás que conformarte con lo ordinario (Jim Rohn)",
    "No mido el éxito de una persona por lo alto que escala, sino por lo rápido que se levanta al caerse (George S. Patton)",
    "Si no construyes tus sueños alguien te contratará para que le ayudes a construir los suyos (Dhirubhai Ambani)",
    "El 80% del éxito es mostrarse (Woody Allen)",
    "Hay dos tipos de personas que te dirán que no puedes marcar una diferencia: los que tienen miedo a intentarlo y los que tienen miedo de que tengas éxito (Ray Goforth)",
    "La gente exitosa y no exitosa no varía mucho en sus habilidades. Varían en sus deseos de alcanzar su potencial (John Maxwell)",
    "Si estableces tus objetivos ridículamente altos y fracasas, habrás fracasado por encima de los éxitos de los demás (James Cameron)",
    "Un hombre puede ser tan grande como quiera ser. Si crees en ti y tienes el coraje, la determinación, la dedicación, el impulso competitivo y la voluntad para sacrificar las cosas pequeñas y pagar por las cosas que merecen la pena, puede ser conseguido (Vince Lombardi)",
    "El éxito es saber tu propósito en la vida, crecer para alcanzar tu máximo potencial y plantar semillas que beneficien a otros (John C. Maxwell)",
    "Nadie te puede hacer sentir inferior sin tu consentimiento (Eleanor Roosevelt)",
    "El único lugar donde el éxito viene antes del trabajo es en el diccionario (Vidal Sassoon)",
    "Si no diseñas tu propio plan de vida, hay muchas oportunidades de que caigas en el plan de otra persona. Y adivina qué han planeado para ti. No mucho (Jim Rohn)",
    "Si quieres conseguir algo grande, para de pedir permiso",
    "El éxito es un malísimo profesor. Seduce a las personas inteligentes para que piensen que no pueden perder (Bill Gates)",
    "Las grandes mentes discuten las ideas; las mentes promedio discuten los acontecimientos; las mentes pequeñas discuten con las personas (Eleanor Roosevelt)",
    "Cuando me atrevo a ser poderoso, a usar mi fuerza en servicio de mi visión, el miedo se convierte en menos importante(Audre Lorde)",
    "Solo tendrás éxito si lo deseas; solo fracasarás si no te importa hacerlo (Philippos)",
    "Una fuerte imagen positiva de uno mismo es el mejor camino hacia el éxito (Joyce Brothers)",
    "El camino hacia el éxito no es fácil de navegar, pero con trabajo duro, y pasión al andarlo es posible conseguir el sueño Americano (Tommy Hilfiger)",
    "Todo lo que necesitas en esta vida es ignorancia y confianza; así el éxito estará asegurado (Mark Twain)",
    "El éxito es donde la preparación y la oportunidad se encuentran (Bobby Unser)",
    "El primer paso hacia el éxito se toma cuando te niegas a ser cautivo del ambiente en el que te encuentras (Mark Caine)",
    "Es importante celebrar el éxito, pero es más importante aprender bien de los fracasos (Bill Gates)",
    "No hay que confundir la verdad con la opinión de la mayoría (Jean Cocteau)",
    "El éxito tiene muchos padres pero el fracaso es huérfano (Napoleón)",
    "Si quieres encontrar la verdadera competencia, sólo mírate en el espejo. Después de un tiempo verás tus rivales luchando por el segundo puesto (Criss Jami)",
    "La peor lucha es la que no se hace (Karl Marx)",
    "Algunas personas quieren que algo ocurra, otras sueñan con qué pasará, otras hacen que suceda (Michael Jordan)",
    "Lo que te define no es cuántas veces te estrellas, sino el número de veces que vuelas (Sarah Dessen)",
    "La confianza en sí mismo es el primer secreto del éxito. (Ralph Waldo Emerson)",
    "Si quieres ir rápido, ve solo. Si quieres llegar lejos, ve acompañado. (Proverbio africano)",
    "No he fracasado. He encontrado 10.000 maneras en las que esto no funciona. (Thomas Edison)",
    "Tanto si crees que eres capaz como si crees que no eres capaz, en ambos casos estás en lo cierto. (Henry Ford)",
    "El único modo de hacer un gran trabajo es amar lo que haces (Steve Jobs)",
    "El talento gana partidos, pero el trabajo en equipo y la inteligencia ganan campeonatos (Michael Jordan)",
    "Hay que apartar de nosotros el mal gusto de querer coincidir con muchos (Friedrich Nietzsche)",
    "Nunca pienso en las consecuencias de fallar un gran tiro… cuando se piensa en las consecuencias se está pensando en un resultado negativo (Michael Jordan)",
    "Ejecuta tus conocimientos con la maestría del que sigue aprendiendo (Jonathan García-Allen)",
    "El dinero no es la clave del éxito; la libertad para poder crear lo es (Nelson Mandela)",
    "No dejes que el éxito se te suba a la cabeza, y no dejes que el fracaso te llegue al corazón (Michael Jordan)",
    "El trabajo duro hace que desaparezcan las arrugas de la mente y el espíritu (Helena Rubinstein)",
    "Cuando llegue la inspiración, que me encuentre trabajando (Pablo Picaso)",
    "El éxito consiste en obtener lo que se desea. La felicidad, en disfrutar lo que se obtiene (Emerson)",
    "El éxito es para los valientes (Proverbio japonés)",
    "He fallado una y otra vez en mi vida, por eso he conseguido el éxito (Michael Jordan)",
    "Tu actitud, no tu aptitud, determina tu altitud (Zig Ziglar)",
    "No busques los errores, busca un remedio (Henry Ford)",
    "Todo el mundo tiene talento, pero la habilidad requiere trabajo duro (Michael Jordan)",
    "Siempre he creído que si uno se pone a trabajar, los resultados llegarán tarde o temprano (Michael Jordan)",
    "Para lograr el éxito, mantenga un aspecto bronceado, viva en un edificio elegante, aunque sea en el sótano, déjese ver en los restaurantes de moda, aunque sólo se tome una copa, y si pide prestado, pida mucho (Aristóteles Onassis)",
    "Se alcanza el éxito convirtiendo cada paso en una meta y cada meta en un paso (Carlos Cortez)",
    "No cuentes los días, haz que los días cuenten (Muhammad Ali)",
    "Para aprender a triunfar primero tienes que aprender a fallar (Michael Jordan)",
    "El éxito consiste en vencer el temor al fracaso (Charles Augustin Sainte-Beuve)",
    "Si la oportunidad no llama, construye una puerta (Milton Berle)",
    "Pocos hombres tienen la fuerza de carácter suficiente para alegrase del éxito de un amigo sin sentir cierta envidia (Esquilo de Eleusis)",
    "Las personas no son recordadas por el número de veces que fracasan, sino por el número de veces que tienen éxito (Thomas Edison)",
    "El éxito es sólo la mitad de bonito cuando no hay nadie que nos envidie (Norman Mailer)",
    "En el mundo común de los hechos, los malos no son castigados y los buenos recompensados. El éxito se lo llevan los fuertes y el fracaso los débiles (Oscar Wilde)",
    "Para obtener éxito en el mundo, hay que parecer loco y ser sabio (Montesquieu)",
    "Si quieres tener éxito, promete todo y no cumplas nada (Napoleón)",
    "Más de uno le debe el éxito a su primera esposa, y su segunda esposa a su éxito (Jim Backus)",
    "Nunca digas nunca. Porque los límites, como el miedo, a menudo son sólo una ilusión (Michael Jordan)",
    "El éxito es fácil de obtener. Lo difícil es merecerlo (Albert Camus)",
    "El valor de una idea radica en su uso (Thomas Edison)",
    "El secreto de mi éxito está en pagar como si fuera pródigo y en vender como si estuviera en quiebra (Henry Ford)",
    "Puedes tener cualquier cosa que quieras si estás dispuesto a renunciar a la creencia de que no lo puedes tener (Dr. Robert Anthony)",
    "A veces se gana y a veces se aprende. (Robert Kiyosaki)",
    "Piensa, sueña, cree y atrévete (Walt Disney)",
    "Si hay un secreto del buen éxito reside en la capacidad para apreciar el punto de vista del prójimo y ver las cosas desde ese punto de vista así como del propio (Henry Ford)",
    "El universo no conspira contra ti, pero tampoco se desvía para alinear tu camino (Tim Ferriss)",
    "Transforma tus heridas en sabiduría (Oprah Winfrey)",
    "La innovación distingue al líder del seguidor (Steve Jobs)",
    "Un bote no va hacia delante si cada uno rema a su propia manera. (Proverbio swahili)",
    "Nunca pares, nunca te conformes, hasta que lo bueno sea mejor y lo mejor excelente. (Anónimo)",
    "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. Si amas lo que haces, tendrás éxito (Albert Schweitzer)",
    "Sé valiente. Toma riesgos. Nada puede sustituir la experiencia (Paulo Coelho)",
    "El éxito no está en vencer siempre, sino en no desanimarse nunca (Napoleón Bonaparte)",
    "Los que tienen éxito tienen impulso. Cuanto más éxito tienen, más quieren lograr, y cuanto más logran, más quieren tener éxito (Tony Robbins)",
    "No te compares con los demás. Compara tu presente con el pasado y con tu propio futuro potencial (William Faulkner)",
    "El éxito no es el dinero o el reconocimiento; el éxito es levantarse cada mañana con un propósito claro (Anónimo)",
    "Solo el que se atreve a fracasar a lo grande puede conseguir grandes cosas (Robert F. Kennedy)",
    "El verdadero éxito es encontrar tu lugar en el mundo y compartirlo con los demás (Bette Midler)",
    "La clave del éxito es empezar antes de estar listo (Marie Forleo)",
    "Para ser insustituible, uno debe buscar siempre ser diferente (Coco Chanel)",
    "El éxito no es el resultado de la combustión espontánea. Debes encenderte a ti mismo (Arnold H. Glasow)",
    "Si te caes siete veces, levántate ocho (Proverbio japonés)",
    "No midas tu éxito por lo que has logrado, sino por los obstáculos que has superado (Booker T. Washington)",
    "El éxito no llega por suerte, sino por insistencia, preparación y visión (Anónimo)",
    "Tener éxito es encontrar el equilibrio entre lo que haces y lo que amas (Simon Sinek)",
    "El éxito no tiene sentido si no puedes compartirlo con quienes amas (Anónimo)",
    "Cuanto más grande es la meta, más profundo debe ser el compromiso (Robin Sharma)",
];
?>